# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
## for gh-packages
#      packages: write

    steps:
    - uses: actions/checkout@v4
      name: Checkout project sources

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4 # v4.0.0

    - name: Build with Gradle
      run: ./gradlew build
      env:
        GITHUB_TAG: ${{ github.event.release.tag_name }}

    - name: Upload Release Asset
      run: |
        gh release upload ${{ github.ref_name }} ./lib/build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

## works but uploads to gh-packages, not the release
#    - name: Publish to GitHub Packages
#      run: ./gradlew publish
#      env:
#        GITHUB_ACTOR: ${{ github.actor }}
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        GITHUB_TAG: ${{ github.event.release.tag_name }}
